//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lg_carLocation
    {
        public int id { get; set; }
        public string car_no { get; set; }
        public string loc { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<System.DateTime> dtime { get; set; }
    }
}
