//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lg_cardBord
    {
        public int id { get; set; }
        public string card_no { get; set; }
        public Nullable<int> car_priority { get; set; }
        public string department { get; set; }
        public string department_pos { get; set; }
        public string status { get; set; }
        public string loader_name { get; set; }
        public string loader_number { get; set; }
        public Nullable<System.DateTime> loader_date { get; set; }
        public string loader_canceller { get; set; }
        public Nullable<System.DateTime> caceller_date { get; set; }
        public string transfer_name { get; set; }
        public string transfer_num { get; set; }
        public Nullable<System.DateTime> transfer_date { get; set; }
        public string receiver_name { get; set; }
        public string receiver_num { get; set; }
        public Nullable<System.DateTime> receiver_date { get; set; }
        public string destination { get; set; }
        public string destination_priority { get; set; }
        public Nullable<int> department_priority { get; set; }
        public string department_contacts { get; set; }
        public string department_contact_email { get; set; }
        public string destination_contacts { get; set; }
        public string destination_contact_email { get; set; }
        public string return_apply_date { get; set; }
        public string return_apply_name { get; set; }
        public string return_status { get; set; }
        public string return_reason { get; set; }
        public Nullable<int> pack_num { get; set; }
        public Nullable<int> is_emergency { get; set; }
        public string mobile_phone { get; set; }
    }
}
