//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lg_truckPermition
    {
        public string account { get; set; }
        public int id { get; set; }
        public int FInterID { get; set; }
        public string FBillNo { get; set; }
        public string FSubmiter { get; set; }
        public Nullable<System.DateTime> FSubDate { get; set; }
        public string FSBillNo { get; set; }
        public string FSInterID { get; set; }
        public Nullable<int> FStatus { get; set; }
        public string FEmpName { get; set; }
        public string FShipToName { get; set; }
        public string FChecker { get; set; }
        public Nullable<System.DateTime> FCheckDate { get; set; }
        public string FItemName { get; set; }
        public string FModel { get; set; }
        public Nullable<decimal> FQty { get; set; }
    }
}
